### ISSUE TITLE
Google Code is no longer available

### ISSUE THREAD

**Issue by digulla** [Mathieuu/CsvEdit#2]
The update site on Google Code is broken; installation via Eclipse Market Place doesn't work anymore and the links on the project page also don't work anymore.

Please disable any unstable features and create a stable 1.2 release.

**Comment by paulvi** [comment]
problem is #3 this repository seems no longer cared for.

**Comment by paulvi** [comment]
published as https://marketplace.eclipse.org/content/csv-edit-resurrector
