### ISSUE TITLE
still maintained?

### ISSUE THREAD

**Issue by ssnyder** [Mathieuu/CsvEdit#3]
Is this still being maintained?  The update site does not seem to be available.

**Comment by paulvi** [comment]
seems not

**Comment by Mathieuu** [comment]
Hi,

Apologize for the very long delay. It has been almost three years I haven't worked with Java and haven't updated the plugin or watched this repo.

Would someone be interested in fixing the marketplace and the other few problems people seem to encounter? Do not hesitate to fork or to open a PR. I can also grant push access if someone is interested in maintaining it.

Best regards,
Mathieu

**Comment by paulvi** [comment]
I can take care (only) of Marketplace entry, see #5 
Anyway there first step would be to build and release in some stable location like bintray.com

**Comment by Mathieuu** [comment]
I have added a warning to the readme signaling that the project is no longer actively maintained.

I also updated the installation guidelines.

**Comment by paulvi** [comment]
@Mathieuu I excepted invitation to join editing this repo.
Though I actually don't have time either  (and even had too much of eclipse plugin to look after https://marketplace.eclipse.org/user/pverest/listings)
I just believe that not deployed code is waste, and Eclipse plugins there must be easy way to install,
that is now p2 repository and listing on Marketplace.

Marketplace related would be discussed in #5 

Already merged optional maven/tycho build #8

**Comment by paulvi** [comment]
Closing this.

Maintain by DoItYourself.
