### ISSUE TITLE
How is this project compared to https://sourceforge.net/projects/csveditor/?

### ISSUE THREAD

**Issue by paulvi** [Mathieuu/CsvEdit#4]
How is this project compared to https://sourceforge.net/projects/csveditor/?

latest commit there 2009

**Comment by Mathieuu** [comment]
This repository is a fork of https://code.google.com/p/csvedit/. It contains additional features that I developed to simplify my day-to-day job when I had tons of csv files to edit.

**Comment by paulvi** [comment]
Have you ever looked into, compared with https://sourceforge.net/projects/csveditor/ ?

**Comment by Mathieuu** [comment]
I don't understand the question. Can you explain?

**Comment by paulvi** [comment]
Do you know if sources of https://sourceforge.net/projects/csveditor/  are related to CsvEdit ?

**Comment by Mathieuu** [comment]
It looks similar, I am not sure about the sources however.

**Comment by paulvi** [comment]
Well, latest commit there was 2009  
https://sourceforge.net/p/csveditor/code/HEAD/tree/  
and there were just 4 commits in total  
https://sourceforge.net/p/csveditor/code/4/log .
