### ISSUE TITLE
Publish as new marketplace entry

### ISSUE THREAD

**Issue by paulvi** [Mathieuu/CsvEdit#5]
There is old marketplace entry https://marketplace.eclipse.org/content/csv-edit that cannot be used.
and the last comment there

> Use https: //raw.githubusercontent.com/SegFaultError/CsvEdit/master/csvedit.update/

 is actually to use https://github.com/Mathieuu/CsvEdit version
(try open https://github.com/SegFaultError/CsvEdit )

Currently marketplace can automatically propose plugin for file extension (e.g. `.csv`) , that would make this plugin discovered by many.

![](https://marketplace.eclipse.org/sites/default/files/styles/ds_solution_screenshot/public/csvedit_main.jpg?itok=11Lr7CDg)

**Comment by paulvi** [comment]
@Mathieuu Do you have access to https://marketplace.eclipse.org/content/csv-edit ?

**Comment by Mathieuu** [comment]
Yes, I have access to the link. I will try to install it this week-end, thanks for the help 👍

**Comment by Mathieuu** [comment]
Adding to the marketplace would require more time than I have to give to this project. However, I fixed the link to install it the old way. 

https://github.com/Mathieuu/CsvEdit/commit/2717006396334b4eca5a7178ba103c3ac54e9102

**Comment by paulvi** [comment]
Trying to contact Frederic Henri via Eclipse Marketplace inquiry...

also #10

**Comment by paulvi** [comment]
Submitted to marketplace, should appear at https://marketplace.eclipse.org/content/csv-edit-resurrector

with Halloween-style logo

![resurrector-csv](https://user-images.githubusercontent.com/1614482/32233944-916b908e-be96-11e7-8d18-3783e6ef7fb5.png)

**Comment by Mathieuu** [comment]
Thanks for your help

**Comment by paulvi** [comment]
Now public at https://marketplace.eclipse.org/content/csv-edit-resurrector
